services:
  code-ords:
    networks:
      - oracle-net
    image: ${ORDS_IMAGE}
    volumes:
      # This points to the new shared Docker volume to allow the apex installation/upgrade to be handled by a separate container
      - code-apex-static-vol:/opt/oracle/ords/static
    ports:
      - target: 8080
        published: ${ORDS_HOST_PORT}
        protocol: tcp
        mode: host
    environment:
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
      - DBSERVICENAME=${DBSERVICENAME}
      - DEPLOY_ID=${DEPLOY_ID}
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo 'The current deployment ID is: ${DEPLOY_ID}'
        echo 'Waiting for database deployment to finish:'
        while [ ! -f /opt/oracle/ords/static/.deploy_ready_${DEPLOY_ID} ]; do
          sleep 5
          echo 'Still waiting for database deployment to finish...'
        done
        echo 'Database Deployment Completed! Injecting secrets and starting ORDS'
        export ORACLE_PWD=$$(cat /run/secrets/oracle_pwd)
        export ORDS_PWD=$$(cat /run/secrets/oracle_pwd)
        ords config set --global standalone.static.path "/opt/oracle/ords/static"
        echo 'Starting official ORDS entrypoint'
        docker-entrypoint.sh
    secrets:
      - oracle_pwd
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure 
        delay: 15s             # Wait 15 seconds before trying again to avoid log spam
        max_attempts: 30       # Allow up to 30 attempts
        window: 600s           # Extend the failure window to 10 minutes
volumes:
  # Defines the new shared volume for the APEX static application files
  code-apex-static-vol:
    external: false
networks: 
  oracle-net:
secrets:
  oracle_pwd:
    name: ${COMPOSE_PROJECT_NAME}_oracle_pwd
    external: true